# Instalacja i załadowanie potrzebnych pakietów

```{r}
BiocManager::install(c("VariantTools", "Rsamtools", "GenomicRanges", "GenomicFeatures", "VariantAnnotation", "BiocParallel", force=TRUE))
```

```{r}
library(VariantTools)
library(Rsamtools)
library(GenomicRanges)
library(GenomicFeatures)
library(VariantAnnotation)
library(BiocParallel)
```

# Konfiguracja środowiska pracy

```{r}
#ustawienie katalogu roboczego:
setwd("C:/Users/48721/Desktop/everything/studia/magisterka/semestr2/R")


#sprawdzenie dostępności plików:
list.files()
```

# Wczytanie danych

```{r}
#wczytanie pliku BAM
bamfile <- "C:/Users/48721/Desktop/everything/studia/magisterka/semestr2/R/aligned_sample1.BAM"
bam <- BamFile(bamfile)

#wczytanie genomu referencyjnego
ref_genome <- "C:/Users/48721/Desktop/everything/studia/magisterka/semestr2/R/ecoli_reference1.fasta"
fa <- FaFile(ref_genome)
```

# Sortowanie plików BAM według współrzędnych

```{r}
#zdefiniowanie ścieżki wejściowej i wyjściowej
input_bam <- "C:/Users/48721/Desktop/everything/studia/magisterka/semestr2/R/aligned_sample.BAM"
output_bam <- "C:/Users/48721/Desktop/everything/studia/magisterka/semestr2/R/sorted_aligned_sample1.BAM"

#sortowanie
sortBam(file = input_bam, destination = output_bam, overwrite = TRUE)

#zdefiniowanie przesortowanego pliku
sorted_bam <- "C:/Users/48721/Desktop/everything/studia/magisterka/semestr2/R/sorted_aligned_sample1.BAM.bam"

#indeksowanie plików FASTA i BAM
indexFa(ref_genome)
indexBam(sorted_bam)
```


# Kontrola jakości danych sekwencyjnych

```{r}
#nagłówek pliku BAM
scanBamHeader(bam)

#podstawowe statystyki pliku BAM
idxstats <- idxstatsBam(sorted_bam)
print(idxstats)

#obliczenie pokrycia genomu
coverage_data <- coverage(sorted_bam)
summary(coverage_data[[1]]) #dla genomów Prokaryota

#wizualizacja pokrycia genomu
plot(coverage_data[[1]], main="Pokrycie genomu dla sekwencji U00096.3", ylab="Pokrycie", xlab="Pozycja w genomie")
```

# Wykrywanie wariantów

```{r}
#ustawienie parametrów pileup
pileup_param <- PileupParam(
    distinguish_strands = FALSE,
    distinguish_nucleotides = TRUE,
    min_base_quality = 20
)

#wykonanie pileup
pile <- pileup(sorted_bam, scanBamParam = ScanBamParam(), pileupParam = pileup_param)

#konwertowanie danych pileup do ramki danych z uzgodnieniem nazw sekwencji
library(dplyr)

pile_df <- as.data.frame(pile)
class(pile_df)

pile_df <- pile_df %>%
    mutate(seqnames = as.character(seqnames)) %>%
    mutate(seqnames = ifelse(seqnames == "U00096.3", "NC_000913.3", seqnames))

#pogrupowanie danych według pozycji
variant_candidates <- pile_df %>%
    group_by(seqnames, pos) %>%
    summarise(
        total = sum(count),
        A = sum(count[nucleotide == "A"]),
        C = sum(count[nucleotide == "C"]),
        G = sum(count[nucleotide == "G"]),
        T = sum(count[nucleotide == "T"]),
        .groups = 'drop'
    ) %>%
    mutate(
        ref = as.character(getSeq(fa, GRanges(seqnames, IRanges(pos, pos))))
    ) %>%
    rowwise() %>%
    mutate(
        #obliczanie alternatywnych alleli
        alt_alleles = list(setdiff(c("A", "C", "G", "T"), ref)),
        #liczenie odczytów dla referencyjnego i alternatywnych alleli
        ref_count = sum(c_across(c("A", "C", "G", "T"))[ref]),
        alt_count = sum(c_across(c("A", "C", "G", "T"))[alt_alleles])
    ) %>%
    ungroup() %>%
    #filtracja na podstawie minimalnej liczby odczytów dla wariantu
    filter(alt_count >= 5) %>%
    #filtrowanie na podstawie proporcji
    filter((alt_count / total) >= 0.2)

#przykład wyświetlenia wariantów
head(variant_candidates)
```

# Filtracja i eksportowanie wyników do pliku

```{r}
#filtracja wariantów na podstawie jakości i głębokości pokrycia
filtered_variants <- variant_candidates %>%
    filter(total >= 10, alt_count / total >= 0.2, alt_count >= 5)

#wyświetlenie liczby wariantów przed i po filtrowaniu
cat("Liczba wariantów przed filtrowaniem:", nrow(variant_candidates), "\n")
cat("Liczba wariantów po filtrowaniu:", nrow(filtered_variants), "\n")

#konwersja do data.frame dla eksportu
df_variants <- as.data.frame(filtered_variants)

#eksport do pliku CSV
write.csv(df_variants, "C:/Users/48721/Desktop/everything/studia/magisterka/semestr2/R/wyniki_wariantow.csv", row.names = FALSE)
```
